cacheFolder: ./.yarn/cache

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-4.4.0.cjs
