# This is the development environment docker-compose.yml
version: '3.9'

x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

services:
  weh:
    image: redis:6.2.6-alpine
    <<: *x-logging
    ports:
      - 6379:6379
    volumes:
      - weh_data:~/.weh:rw
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s

networks:
  default:
    driver: overlay
    attachable: true

volumes:
  weh_data:
